// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCphvlQix94O2383HT_gnIHgdLmHVwke1E',
    appId: '1:955729406530:web:0870fc6c15465e4aca9bdb',
    messagingSenderId: '955729406530',
    projectId: 'labours-235b7',
    authDomain: 'labours-235b7.firebaseapp.com',
    storageBucket: 'labours-235b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKOCyiztGejl-JoYaKlDIsbTsXUg8n2yI',
    appId: '1:955729406530:android:385197f4205cb7d2ca9bdb',
    messagingSenderId: '955729406530',
    projectId: 'labours-235b7',
    storageBucket: 'labours-235b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2JNpsN8Q2-xucHE90zhbtvT6Rue_1j5s',
    appId: '1:955729406530:ios:48f29a6a2bca1637ca9bdb',
    messagingSenderId: '955729406530',
    projectId: 'labours-235b7',
    storageBucket: 'labours-235b7.firebasestorage.app',
    iosBundleId: 'com.example.labours',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2JNpsN8Q2-xucHE90zhbtvT6Rue_1j5s',
    appId: '1:955729406530:ios:48f29a6a2bca1637ca9bdb',
    messagingSenderId: '955729406530',
    projectId: 'labours-235b7',
    storageBucket: 'labours-235b7.firebasestorage.app',
    iosBundleId: 'com.example.labours',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCphvlQix94O2383HT_gnIHgdLmHVwke1E',
    appId: '1:955729406530:web:2e73011947f16bf4ca9bdb',
    messagingSenderId: '955729406530',
    projectId: 'labours-235b7',
    authDomain: 'labours-235b7.firebaseapp.com',
    storageBucket: 'labours-235b7.firebasestorage.app',
  );
}
